---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi
status: {}