apiVersion: v1
kind: Secret
metadata:
    name: keycloak-sso-data
type: Opaque
stringData:
    CLIENT_ID: ${FORWARD_AUTH_CLIENT_ID}
    CLIENT_SECRET: ${FORWARD_AUTH_CLIENT_SECRET}
    ENCRYPTION_KEY: ""
    PROVIDER_URI: https://traefik-forward-auth.traunseenet.com/realms/master
    SECRET: ${FORWARD_AUTH_SECRET}
    AUTH_HOST: https://traefik-forward-auth.traunseenet.com
    COOKIE_DOMAIN: traunseenet.com
    # DEFAULT_PROVIDER: generic-oauth
    DEFAULT_PROVIDER: oidc
    PROVIDERS_OIDC_ISSUER_URL: https://keycloak-prod.traunseenet.com/realms/master
    PROVIDERS_OIDC_CLIENT_ID: ${FORWARD_AUTH_CLIENT_ID}
    PROVIDERS_OIDC_CLIENT_SECRET: ${FORWARD_AUTH_CLIENT_SECRET}