apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_ENDPOINTS: ${AWS_ENDPOINTS}