apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
- storage-classes.yaml
- backup-secret.yaml
- ingress-local.yaml
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    namespace: longhorn
    valuesFile: values.yaml
    version: 1.7.2