apiVersion: v1
data:
  MYSQL_PASSWORD: ${NEXCLOUD_DB_PWD}
  MYSQL_ROOT_PASSWORD: ${NEXCLOUD_ADMIN_DB_PWD}
  MYSQL_USER: ${NEXTCLOUD_DB_USER}
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
