apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: nextcloud-service
  namespace: nextcloud
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https-443
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nextcloud
  sessionAffinity: None
  type: ClusterIP
