apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: nextcloud-db-service
  namespace: nextcloud
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    pod-label: nextcloud-db-pod
  sessionAffinity: None
  type: ClusterIP
