apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# unused due to lack of interest - audiobookshelf
- cert-manager
- forward-auth
- headscale
- homepage
- immich
- jellyfin
#- keycloak todo, search for correct helm chart link
- longhorn
- minio
- navidrome
# unused due to resource constraints - observability
# unused due to resource constraints - openwebui
- paperless
- registry
- seafile
- traefik
- utility