apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
- ingress.yaml
helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com/
    releaseName: open-webui
    namespace: open-webui
    valuesFile: values.yaml