---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-llm-longhorn
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 50Gi
status: {}