apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-02-15T17:56:25Z"
      labels:
        app: nextcloud
    spec:
      containers:
        - env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "992"
            - name: TZ
              value: Europe/Amsterdam
          image: ghcr.io/linuxserver/nextcloud
          imagePullPolicy: Always
          name: nextcloud
          ports:
            - containerPort: 443
              name: https-443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: nfs-nextcloud
              subPath: config
            - mountPath: /data
              name: nfs-nextcloud
              subPath: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nfs-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-server-pvc
        - name: nextcloud-ssl
          secret:
            defaultMode: 420
            secretName: nextcloud-net-tls
