apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- configmap-acl.yaml
- ingress-server.yaml
#- pvc.yaml