apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts/keycloak
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml