---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-keycloak-postgresql-0
  namespace: keycloak
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/keycloak/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-keycloak-postgresql-0
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: postgresql
spec:
  volumeMode: Filesystem
  volumeName: data-keycloak-postgresql-0
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi