apiVersion: v1
kind: Secret
metadata:
    namespace: keycloak
    name: keycloak-auth
type: Opaque
stringData:
    KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
    KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    PGR_USER: ${DB_USER}
    PGR_DB: ${DB_NAME}
    PGR_PASS: ${DB_PASSWORD}
    password: ${DB_PASSWORD}
    postgres-password: ${DB_PASSWORD}