---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-longhorn
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi
status: {}