apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
- ingress.yaml
#- pvc.yaml #only used for initial setup, restore from longhorn if lost
helmCharts:
  - name: paperless-ngx
    repo: https://charts.gabe565.com/
    releaseName: paperless-ngx
    namespace: paperless
    valuesFile: values.yaml