#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/paperless-ngx/paperless-ngx
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 2.11.6

# -- Environment variables [[ref]](https://docs.paperless-ngx.com/configuration/)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- Set the container timezone
  TZ: "Europe/Vienna"
  PAPERLESS_OCR_PAGES: 1
  PAPERLESS_TASK_WORKERS: 2
  PAPERLESS_THREADS_PER_WORKER: 1
  PAPERLESS_OCR_SKIP_ARCHIVE_FILE: "with_text"
  PAPERLESS_WEBSERVER_WORKERS: 1
  PAPERLESS_OCR_LANGUAGES: "deu+eng"
  PAPERLESS_SECRET_KEY: "${PAPERLESS_SECRET_KEY}"
  PAPERLESS_URL: "https://paperless.local.traunseenet.com"
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect": {"APPS": [{"provider_id": "keycloak","name": "Keycloak","client_id": "${PAPERLESS_CLIENT_ID}","secret": "${PAPERLESS_CLIENT_SECRET}","settings": { "server_url": "${PAPERLESS_OPENID_PROVIDER_URL}"}}]}}'
  PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: false
  PAPERLESS_DISABLE_REGULAR_LOGIN: true
  # SSO documentation: https://docs.paperless-ngx.com/advanced_usage/#openid-connect-and-social-authentication
service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: true
    storageClass: "longhorn-storage"
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure media volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  media:
    enabled: true
    storageClass: "longhorn-storage"
    accessMode: ReadWriteOnce
    size: 8Gi
  # -- Configure export volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  export:
    enabled: true
    storageClass: "longhorn-storage"
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure consume volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  consume:
    enabled: true
    storageClass: "longhorn-storage"
    accessMode: ReadWriteOnce
    size: 4Gi

# -- Enable and configure postgresql database subchart under this key.
#    If enabled, the app's db envs will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: true
  auth:
    database: ${PAPERLESS_POSTGRES_DATABASE_NAME}
    postgresPassword: ${PAPERLESS_POSTGRES_DATABASE_PWD}
  primary:
    persistence:
      enabled: true
      storageClass: "longhorn-storage"
      size: 8Gi

# -- Enable and configure mariadb database subchart under this key.
#    If enabled, the app's db envs will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
mariadb:
  enabled: false
  auth:
    database: paperless
    username: paperless
    password: changeme
    rootPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

# -- Enable and configure redis subchart under this key.
#    If enabled, the app's Redis env will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/redis)
# @default -- See [values.yaml](./values.yaml)
redis:
  enabled: true
  image:
    repository: bitnami/redis
    tag: 7.2.4-debian-12-r12
    pullPolicy: IfNotPresent
  auth:
    enabled: true
    username: "${PAPERLESS_REDIS_UNAME}"
    # Use an existing secret for redis auth. Do this if you're using Argo to manage your instance or otherwise using helm template under the hood
    #     The secret name can vary, but the password key must be redis-password.
    # existingSecret: paperless-redis
    # existingSecretPasswordKey: redis-password
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
