apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
resources:
- deployment.yaml
- ingress.yaml
- ingress-classic.yaml
#- pvc.yaml #only used for initial setup, restore from longhorn if lost
- service.yaml
