apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml