apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
- ingress.yaml
- pvc.yaml
helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml