apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
- ingress-public.yaml
#- pvc.yaml #only used for initial setup, restore from longhorn if lost
helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml
    version: 0.8.1