provisionDataStore:
  cassandra: false
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
allInOne:
  enabled: true
  ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: traefik
    # labels: {}
    # Used to create an Ingress record.
    hosts:
      - jaeger.traunseenet.com
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
    labels:
      app.kubernetes.io/name: jaeger
    tls:
      # Secrets must be manually created in the namespace.
      - secretName: letsencrypt-prod
        hosts:
          - jaeger.traunseenet.com