---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-data
  namespace: jellyfin
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/jellyfin/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-config
  namespace: jellyfin
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/jellyfin/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-data
spec:
  volumeMode: Filesystem
  volumeName: jellyfin-pv-data
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-config
spec:
  volumeMode: Filesystem
  volumeName: jellyfin-pv-config
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi