apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portainer
helmCharts:
  - name: portainer
    repo: https://portainer.github.io/k8s/
    releaseName: portainer
    namespace: portainer
    valuesFile: values.yaml