---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv-server
  namespace: nextcloud
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/nextcloud/server"