---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv-data
  namespace: nextcloud
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/nextcloud/db"